// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/web.proto

/*
Package server is a generated protocol buffer package.

Web exposes a backend server over gRPC.

It is generated from these files:
	proto/web.proto

It has these top-level messages:
	Backend
	ProxyState
	OpResult
	StateRequest
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/johanbrandhorst/protobuf/proto"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Backend struct {
	Domain       string   `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
	Ips          []string `protobuf:"bytes,2,rep,name=ips" json:"ips,omitempty"`
	HealthCheck  string   `protobuf:"bytes,3,opt,name=health_check,json=healthCheck" json:"health_check,omitempty"`
	HealthStatus string   `protobuf:"bytes,4,opt,name=health_status,json=healthStatus" json:"health_status,omitempty"`
}

func (m *Backend) Reset()                    { *m = Backend{} }
func (m *Backend) String() string            { return proto.CompactTextString(m) }
func (*Backend) ProtoMessage()               {}
func (*Backend) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Backend) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Backend) GetIps() []string {
	if m != nil {
		return m.Ips
	}
	return nil
}

func (m *Backend) GetHealthCheck() string {
	if m != nil {
		return m.HealthCheck
	}
	return ""
}

func (m *Backend) GetHealthStatus() string {
	if m != nil {
		return m.HealthStatus
	}
	return ""
}

type ProxyState struct {
	Backends []*Backend `protobuf:"bytes,1,rep,name=backends" json:"backends,omitempty"`
	// a status message, or an error message.
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	// an error code
	Code int32 `protobuf:"varint,3,opt,name=code" json:"code,omitempty"`
}

func (m *ProxyState) Reset()                    { *m = ProxyState{} }
func (m *ProxyState) String() string            { return proto.CompactTextString(m) }
func (*ProxyState) ProtoMessage()               {}
func (*ProxyState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProxyState) GetBackends() []*Backend {
	if m != nil {
		return m.Backends
	}
	return nil
}

func (m *ProxyState) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ProxyState) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type OpResult struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *OpResult) Reset()                    { *m = OpResult{} }
func (m *OpResult) String() string            { return proto.CompactTextString(m) }
func (*OpResult) ProtoMessage()               {}
func (*OpResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *OpResult) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *OpResult) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type StateRequest struct {
	// if domain is empty string, return "all" states, otherwise
	// match domain DNS-style, e.g. google.com matches docs.google.com
	Domain string `protobuf:"bytes,1,opt,name=domain" json:"domain,omitempty"`
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *StateRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func init() {
	proto.RegisterType((*Backend)(nil), "web.Backend")
	proto.RegisterType((*ProxyState)(nil), "web.ProxyState")
	proto.RegisterType((*OpResult)(nil), "web.OpResult")
	proto.RegisterType((*StateRequest)(nil), "web.StateRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Proxy service

type ProxyClient interface {
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*ProxyState, error)
	Put(ctx context.Context, in *Backend, opts ...grpc.CallOption) (*OpResult, error)
	Remove(ctx context.Context, in *Backend, opts ...grpc.CallOption) (*OpResult, error)
}

type proxyClient struct {
	cc *grpc.ClientConn
}

func NewProxyClient(cc *grpc.ClientConn) ProxyClient {
	return &proxyClient{cc}
}

func (c *proxyClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*ProxyState, error) {
	out := new(ProxyState)
	err := grpc.Invoke(ctx, "/web.Proxy/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Put(ctx context.Context, in *Backend, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := grpc.Invoke(ctx, "/web.Proxy/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *proxyClient) Remove(ctx context.Context, in *Backend, opts ...grpc.CallOption) (*OpResult, error) {
	out := new(OpResult)
	err := grpc.Invoke(ctx, "/web.Proxy/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Proxy service

type ProxyServer interface {
	State(context.Context, *StateRequest) (*ProxyState, error)
	Put(context.Context, *Backend) (*OpResult, error)
	Remove(context.Context, *Backend) (*OpResult, error)
}

func RegisterProxyServer(s *grpc.Server, srv ProxyServer) {
	s.RegisterService(&_Proxy_serviceDesc, srv)
}

func _Proxy_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.Proxy/State",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).State(ctx, req.(*StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Backend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.Proxy/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Put(ctx, req.(*Backend))
	}
	return interceptor(ctx, in, info, handler)
}

func _Proxy_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Backend)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/web.Proxy/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServer).Remove(ctx, req.(*Backend))
	}
	return interceptor(ctx, in, info, handler)
}

var _Proxy_serviceDesc = grpc.ServiceDesc{
	ServiceName: "web.Proxy",
	HandlerType: (*ProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "State",
			Handler:    _Proxy_State_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _Proxy_Put_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Proxy_Remove_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/web.proto",
}

func init() { proto.RegisterFile("proto/web.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xc1, 0xaf, 0xd2, 0x40,
	0x10, 0xc6, 0x29, 0x05, 0x84, 0x01, 0x82, 0xee, 0xc1, 0x34, 0x9c, 0xb0, 0x1a, 0xed, 0x05, 0x6a,
	0x30, 0x31, 0x1e, 0x15, 0x8d, 0x57, 0x49, 0xb9, 0x79, 0x31, 0xbb, 0xdb, 0x91, 0x2d, 0x94, 0x6e,
	0xdd, 0xdd, 0x82, 0xc6, 0xb3, 0xff, 0xb4, 0xa7, 0x97, 0xee, 0xf6, 0xc1, 0x7b, 0x07, 0xf2, 0xf2,
	0x6e, 0xf3, 0xcd, 0x7c, 0xb3, 0xf9, 0x7d, 0x9b, 0x81, 0x49, 0xa9, 0xa4, 0x91, 0xf1, 0x09, 0xd9,
	0xc2, 0x56, 0xc4, 0x3f, 0x21, 0x9b, 0x7e, 0xd8, 0x66, 0x46, 0x54, 0x6c, 0xc1, 0xe5, 0x21, 0xde,
	0x49, 0x41, 0x0b, 0xa6, 0x68, 0x91, 0x0a, 0xa9, 0xb4, 0x89, 0xad, 0x8d, 0x55, 0x3f, 0x5d, 0x11,
	0x6f, 0x65, 0x29, 0x50, 0xed, 0xb4, 0x5b, 0x0f, 0xff, 0xc2, 0x93, 0x15, 0xe5, 0x7b, 0x2c, 0x52,
	0xf2, 0x1c, 0x7a, 0xa9, 0x3c, 0xd0, 0xac, 0x08, 0xbc, 0x99, 0x17, 0x0d, 0x92, 0x46, 0x91, 0xa7,
	0xe0, 0x67, 0xa5, 0x0e, 0xda, 0x33, 0x3f, 0x1a, 0x24, 0x75, 0x49, 0x5e, 0xc0, 0x48, 0x20, 0xcd,
	0x8d, 0xf8, 0xc1, 0x05, 0xf2, 0x7d, 0xe0, 0x5b, 0xff, 0xd0, 0xf5, 0x3e, 0xd7, 0x2d, 0xf2, 0x12,
	0xc6, 0x8d, 0x45, 0x1b, 0x6a, 0x2a, 0x1d, 0x74, 0xac, 0xa7, 0xd9, 0xdb, 0xd8, 0x5e, 0xc8, 0x00,
	0xd6, 0x4a, 0xfe, 0xfe, 0x53, 0x4b, 0x24, 0x11, 0xf4, 0x99, 0x43, 0xd1, 0x81, 0x37, 0xf3, 0xa3,
	0xe1, 0x72, 0xb4, 0xa8, 0x73, 0x36, 0x7c, 0xc9, 0x79, 0x5a, 0x93, 0x36, 0xaf, 0xb6, 0x1d, 0xa9,
	0x53, 0x84, 0x40, 0x87, 0xcb, 0x14, 0x2d, 0x4f, 0x37, 0xb1, 0x75, 0xf8, 0x1e, 0xfa, 0xdf, 0xca,
	0x04, 0x75, 0x95, 0x9b, 0xf3, 0xdc, 0xbb, 0xcc, 0xaf, 0xbd, 0x15, 0xbe, 0x86, 0x91, 0xc5, 0x4a,
	0xf0, 0x57, 0x85, 0xda, 0x5c, 0xfb, 0x9d, 0xe5, 0x3f, 0x0f, 0xba, 0x36, 0x04, 0x99, 0x43, 0xd7,
	0x05, 0x79, 0x66, 0xb1, 0xef, 0x6e, 0x4f, 0x27, 0xb6, 0x75, 0x09, 0x1b, 0xb6, 0xc8, 0x2b, 0xf0,
	0xd7, 0x95, 0x21, 0xf7, 0x32, 0x4e, 0xc7, 0x56, 0xdd, 0x02, 0x87, 0x2d, 0xf2, 0x06, 0x7a, 0x09,
	0x1e, 0xe4, 0x11, 0x1f, 0x30, 0xae, 0xf0, 0xff, 0xc7, 0xb7, 0xdb, 0xcc, 0xe4, 0xd4, 0x5d, 0xc1,
	0x97, 0xcd, 0xa7, 0x0d, 0x2d, 0xbe, 0x2a, 0x5a, 0xf0, 0x4c, 0x73, 0x19, 0x73, 0x39, 0xe7, 0x82,
	0x66, 0xaa, 0xb9, 0x02, 0x9e, 0x67, 0x58, 0x98, 0xef, 0x8f, 0xd8, 0xd0, 0xa8, 0x8e, 0xa8, 0x58,
	0xcf, 0xaa, 0x77, 0x37, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0xd4, 0x20, 0xad, 0x88, 0x02, 0x00,
	0x00,
}
